# Generated by Django 3.2.13 on 2023-02-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroSubmits',
            new_name='HeroSubmit',
        ),
    ]
