# Generated by Django 3.2.13 on 2023-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_herosubmits_herosubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
    ]
