# Generated by Django 3.2.13 on 2023-02-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contactsubmit_modelsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmit',
            name='mail_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herosubmit',
            name='mail_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelsubmit',
            name='mail_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
